/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#050810',
        surface: '#0A1128',
        'surface-variant': '#1C2541',
        'surface-container': '#131A2B',
        'surface-container-high': '#182136',
        'surface-container-highest': '#1D2841',
        'on-surface': '#F8FAFC',
        'on-surface-variant': '#94A3B8',
        primary: '#06B6D4',
        'on-primary': '#FFFFFF',
        'primary-container': '#0891B2',
        'on-primary-container': '#E0F2FE',
        secondary: '#3B82F6',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#2563EB',
        'on-secondary-container': '#DBEAFE',
        tertiary: '#8B5CF6',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': '#7C3AED',
        'on-tertiary-container': '#EDE9FE',
        error: '#EF4444',
        'on-error': '#FFFFFF',
        'error-container': '#DC2626',
        'on-error-container': '#FEE2E2',
        'outline': '#475569',
        'outline-variant': '#334155',
      },
      fontFamily: {
        'headline-display': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'data-tabular': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-display': ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'data-tabular': ['13px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      spacing: {
        'unit': '4px',
        'gutter': '24px',
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
}
