"""add_terminology_mapping_metadata

Revision ID: 2c461390691d
Revises: 8ba856e6c5cc
Create Date: 2026-09-23 08:36:32.316185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c461390691d'
down_revision = '8ba856e6c5cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mapping_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mapping_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mapping_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mapping_provenance', sa.String(length=100), nullable=True))

    with op.batch_alter_table('correction_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('extracted_field_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('document_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('reviewer_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mapping_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mapping_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mapping_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mapping_provenance', sa.String(length=100), nullable=True))

    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mapping_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mapping_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mapping_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mapping_provenance', sa.String(length=100), nullable=True))

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mapping_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mapping_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mapping_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mapping_provenance', sa.String(length=100), nullable=True))

    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mapping_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mapping_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mapping_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mapping_provenance', sa.String(length=100), nullable=True))

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.drop_column('mapping_provenance')
        batch_op.drop_column('mapping_confidence')
        batch_op.drop_column('mapping_version')
        batch_op.drop_column('mapping_status')

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_column('mapping_provenance')
        batch_op.drop_column('mapping_confidence')
        batch_op.drop_column('mapping_version')
        batch_op.drop_column('mapping_status')

    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.drop_column('mapping_provenance')
        batch_op.drop_column('mapping_confidence')
        batch_op.drop_column('mapping_version')
        batch_op.drop_column('mapping_status')

    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.drop_column('mapping_provenance')
        batch_op.drop_column('mapping_confidence')
        batch_op.drop_column('mapping_version')
        batch_op.drop_column('mapping_status')

    with op.batch_alter_table('correction_logs', schema=None) as batch_op:
        batch_op.alter_column('reviewer_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('document_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('extracted_field_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.drop_column('mapping_provenance')
        batch_op.drop_column('mapping_confidence')
        batch_op.drop_column('mapping_version')
        batch_op.drop_column('mapping_status')

    # ### end Alembic commands ###
