"""Add extraction versioning

Revision ID: 3f3fb43f0864
Revises: ee5275fd9a81
Create Date: 2026-09-22 15:54:44.223946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3fb43f0864'
down_revision = 'ee5275fd9a81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('extractor_name', sa.String(length=100), nullable=False),
    sa.Column('extractor_version', sa.String(length=100), nullable=False),
    sa.Column('config_version', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('supersedes_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_run_id'], ['extraction_runs.run_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('extraction_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_runs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_runs_run_id'), ['run_id'], unique=False)



    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_extraction_run_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('document_version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('fk_documents_current_extraction_run_id', 'extraction_runs', ['current_extraction_run_id'], ['run_id'], ondelete='SET NULL')

    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extraction_run_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_extracted_fields_extraction_run_id'), ['extraction_run_id'], unique=False)
        batch_op.create_foreign_key('fk_extracted_fields_extraction_run_id', 'extraction_runs', ['extraction_run_id'], ['run_id'], ondelete='CASCADE')

    # Backfill legacy extraction runs
    connection = op.get_bind()
    import uuid
    docs = connection.execute(sa.text("SELECT DISTINCT document_id FROM extracted_fields")).fetchall()
    for doc in docs:
        doc_id = doc[0]
        run_id = str(uuid.uuid4())
        connection.execute(sa.text(
            f"INSERT INTO extraction_runs (run_id, document_id, extractor_name, extractor_version, status, created_at) "
            f"VALUES ('{run_id}', '{doc_id}', 'legacy_extractor', '1.0', 'completed', CURRENT_TIMESTAMP)"
        ))
        connection.execute(sa.text(
            f"UPDATE extracted_fields SET extraction_run_id = '{run_id}' WHERE document_id = '{doc_id}'"
        ))
        connection.execute(sa.text(
            f"UPDATE documents SET current_extraction_run_id = '{run_id}' WHERE document_id = '{doc_id}'"
        ))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.drop_constraint('fk_extracted_fields_extraction_run_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_extracted_fields_extraction_run_id'))
        batch_op.drop_column('extraction_run_id')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_current_extraction_run_id', type_='foreignkey')
        batch_op.drop_column('document_version')
        batch_op.drop_column('current_extraction_run_id')



    with op.batch_alter_table('extraction_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_extraction_runs_document_id'))

    op.drop_table('extraction_runs')
    # ### end Alembic commands ###
