"""Add rag_messages table

Revision ID: 8ba856e6c5cc
Revises: 3f3fb43f0864
Create Date: 2026-09-23 08:16:21.774099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8ba856e6c5cc'
down_revision = '3f3fb43f0864'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['rag_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_messages_id'), ['id'], unique=False)

    pass

    with op.batch_alter_table('rag_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('turns')

    pass

    # ### end Alembic commands ###


def downgrade() -> None:
    pass

    with op.batch_alter_table('rag_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turns', sqlite.JSON(), nullable=False))
        batch_op.drop_column('expires_at')

    pass
    with op.batch_alter_table('rag_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_messages_id'))
        batch_op.drop_index(batch_op.f('ix_rag_messages_conversation_id'))

    op.drop_table('rag_messages')
    # ### end Alembic commands ###
