"""create_scheduled_reports

Revision ID: c310214221a4
Revises: 2c461390691d
Create Date: 2026-09-23 09:03:57.196476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c310214221a4'
down_revision = '2c461390691d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_reports',
    sa.Column('id', sa.String(), server_default=sa.text('(lower(hex(randomblob(16))))'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('report_definition', sqlite.JSON(), nullable=False),
    sa.Column('schedule', sa.String(), nullable=False),
    sa.Column('output_format', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('failure_state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_reports_user_id'), ['user_id'], unique=False)

    # removed batch alter tables for id that were failing

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('correction_logs', schema=None) as batch_op:
        batch_op.alter_column('reviewer_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('document_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('extracted_field_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('scheduled_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_reports_user_id'))

    op.drop_table('scheduled_reports')
    # ### end Alembic commands ###
