"""add_patient_access_to_users

Revision ID: d84d7da68980
Revises: 2753d494539d
Create Date: 2026-08-13 17:59:42.880134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'd84d7da68980'
down_revision = '2753d494539d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_rag_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.document_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_rag_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_rag_chunks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_rag_chunks_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('extraction_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_fields_document_id'))
        batch_op.drop_index(batch_op.f('ix_extraction_fields_field_id'))

    op.drop_table('extraction_fields')
    with op.batch_alter_table('correction_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('extracted_field_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('document_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('reviewer_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_patient_id'), ['patient_id'], unique=False)
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['patient_id'])

    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_fields_verification_status'), ['verification_status'], unique=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_number', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_patient_number'), ['patient_number'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_access', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), server_default='{}', nullable=False, comment='Explicit patient UUIDs this user may access. Empty = no restriction for admin role only.'))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('visit_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('provider_name', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_visits_document_id'), ['document_id'], unique=False)
        batch_op.create_foreign_key(None, 'documents', ['document_id'], ['document_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_visits_document_id'))
        batch_op.drop_column('provider_name')
        batch_op.drop_column('visit_type')
        batch_op.drop_column('document_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('patient_access')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_patient_number'))
        batch_op.drop_column('patient_number')

    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_fields_verification_status'))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_patient_id'))

    with op.batch_alter_table('correction_logs', schema=None) as batch_op:
        batch_op.alter_column('reviewer_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('document_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('extracted_field_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.create_table('extraction_fields',
    sa.Column('field_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('document_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('raw_value', sa.VARCHAR(length=500), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bounding_box', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('field_id')
    )
    with op.batch_alter_table('extraction_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_fields_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_fields_document_id'), ['document_id'], unique=False)

    with op.batch_alter_table('patient_rag_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_rag_chunks_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_rag_chunks_id'))

    op.drop_table('patient_rag_chunks')
    # ### end Alembic commands ###
