"""apply_schema_governance

Revision ID: ee5275fd9a81
Revises: e732bd510d82
Create Date: 2026-09-22 13:33:02.444785

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'ee5275fd9a81'
down_revision = 'e732bd510d82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_rag_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_document_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_rag_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_rag_chunks_source_document_id'), ['source_document_id'], unique=False)

    op.create_table('rag_conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('turns', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_conversations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('upload_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_logs_id'), ['id'], unique=False)

    op.create_table('canonical_patient_records',
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('source_field_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('document_id', 'field_name', name='uq_canonical_document_field')
    )
    with op.batch_alter_table('canonical_patient_records', schema=None) as batch_op:
        batch_op.create_index('ix_canonical_patient_records_document', ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_patient_records_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_patient_records_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_patient_records_source_field_id'), ['source_field_id'], unique=False)

    op.create_table('layout_regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('region_type', sa.String(length=50), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('layout_regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_layout_regions_document_id'), ['document_id'], unique=False)


    with op.batch_alter_table('audit_log_entries', schema=None) as batch_op:
        batch_op.alter_column('log_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.audit_log.GUID(length=36),
               existing_nullable=False)
        batch_op.alter_column('actor_user_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.audit_log.GUID(length=36),
               existing_nullable=False)

    with op.batch_alter_table('correction_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('extracted_field_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('document_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('reviewer_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_correction_logs_action'))
        batch_op.drop_index(batch_op.f('idx_correction_logs_document'))
        batch_op.drop_index(batch_op.f('idx_correction_logs_exported'))
        batch_op.drop_index(batch_op.f('idx_correction_logs_field'))
        batch_op.drop_index(batch_op.f('idx_correction_logs_reviewer'))
        batch_op.drop_index(batch_op.f('idx_correction_logs_verified'), sqlite_where=sa.text('verified_at IS NOT NULL'))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=500), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('QUEUED', 'NEW', 'PREPROCESSING', 'DETECTING_LAYOUT', 'CLASSIFYING', 'EXTRACTING', 'PREPROCESSED', 'CLASSIFIED', 'EXTRACTED', 'UNLINKED', 'PENDING_REVIEW', 'COMMITTED', 'FAILED', name='documentstatus'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_documents_document_id'), ['document_id'], unique=False)

    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_fields_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_field_name'), ['field_name'], unique=False)
        batch_op.create_check_constraint('ck_extracted_fields_confidence_range', 'confidence_score >= 0.0 AND confidence_score <= 1.0')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_notes_author_id'))
        batch_op.drop_index(batch_op.f('idx_notes_patient_id'))

    with op.batch_alter_table('patient_duplicate_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_patient_duplicate_pair'))

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admission_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('discharge_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_column('discharge_date')
        batch_op.drop_column('admission_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'"))

    with op.batch_alter_table('patient_duplicate_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_patient_duplicate_pair'), ['patient_a_id', 'patient_b_id'], unique=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_notes_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_notes_author_id'), ['author_id'], unique=False)

    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.drop_constraint('ck_extracted_fields_confidence_range', type_='check')
        batch_op.drop_index(batch_op.f('ix_extracted_fields_field_name'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_field_id'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_document_id'))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_document_id'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('QUEUED', 'NEW', 'PREPROCESSING', 'DETECTING_LAYOUT', 'CLASSIFYING', 'EXTRACTING', 'PREPROCESSED', 'CLASSIFIED', 'EXTRACTED', 'UNLINKED', 'PENDING_REVIEW', 'COMMITTED', 'FAILED', name='documentstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('rejection_reason')

    with op.batch_alter_table('correction_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_correction_logs_verified'), ['verified_at'], unique=False, sqlite_where=sa.text('verified_at IS NOT NULL'))
        batch_op.create_index(batch_op.f('idx_correction_logs_reviewer'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_correction_logs_field'), ['extracted_field_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_correction_logs_exported'), ['retraining_exported'], unique=False)
        batch_op.create_index(batch_op.f('idx_correction_logs_document'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_correction_logs_action'), ['action'], unique=False)
        batch_op.alter_column('reviewer_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('document_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('extracted_field_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('audit_log_entries', schema=None) as batch_op:
        batch_op.alter_column('actor_user_id',
               existing_type=app.models.audit_log.GUID(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('log_id',
               existing_type=app.models.audit_log.GUID(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)



    with op.batch_alter_table('layout_regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_layout_regions_document_id'))

    op.drop_table('layout_regions')
    with op.batch_alter_table('canonical_patient_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canonical_patient_records_source_field_id'))
        batch_op.drop_index(batch_op.f('ix_canonical_patient_records_field_name'))
        batch_op.drop_index(batch_op.f('ix_canonical_patient_records_document_id'))
        batch_op.drop_index('ix_canonical_patient_records_document')

    op.drop_table('canonical_patient_records')
    with op.batch_alter_table('upload_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_logs_id'))

    op.drop_table('upload_logs')
    with op.batch_alter_table('rag_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_rag_conversations_patient_id'))
        batch_op.drop_index(batch_op.f('ix_rag_conversations_id'))

    op.drop_table('rag_conversations')
    with op.batch_alter_table('policy_rag_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_rag_chunks_source_document_id'))

    op.drop_table('policy_rag_chunks')
    # ### end Alembic commands ###
