"""Add audit log entry

Revision ID: f77d5b30acdc
Revises: 92cec2883fc9
Create Date: 2026-08-18 15:25:31.227125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77d5b30acdc'
down_revision = '92cec2883fc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entries',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_entity', sa.String(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('audit_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entries_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entries_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entries_timestamp'), ['timestamp'], unique=False)

    # Only audit_log_entries changes are kept here to resolve merge conflicts

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only audit_log_entries changes are kept here to resolve merge conflicts

    with op.batch_alter_table('audit_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_action_type'))

    op.drop_table('audit_log_entries')
    # ### end Alembic commands ###
