"""Add audit log entry

Revision ID: f77d5b30acdc
Revises: 92cec2883fc9
Create Date: 2026-08-18 15:25:31.227125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77d5b30acdc'
down_revision = '92cec2883fc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entries',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_entity', sa.String(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('audit_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entries_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entries_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entries_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('correction_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('extracted_field_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('document_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('reviewer_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_correction_logs_action'))
        batch_op.drop_index(batch_op.f('idx_correction_logs_document'))
        batch_op.drop_index(batch_op.f('idx_correction_logs_exported'))
        batch_op.drop_index(batch_op.f('idx_correction_logs_field'))
        batch_op.drop_index(batch_op.f('idx_correction_logs_reviewer'))
        batch_op.drop_index(batch_op.f('idx_correction_logs_verified'), sqlite_where=sa.text('verified_at IS NOT NULL'))

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_number', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_patient_number'), ['patient_number'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_access', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('visit_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('provider_name', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_visits_document_id'), ['document_id'], unique=False)
        batch_op.create_foreign_key(None, 'documents', ['document_id'], ['document_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_visits_document_id'))
        batch_op.drop_column('provider_name')
        batch_op.drop_column('visit_type')
        batch_op.drop_column('document_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('patient_access')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_patient_number'))
        batch_op.drop_column('patient_number')

    with op.batch_alter_table('correction_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_correction_logs_verified'), ['verified_at'], unique=False, sqlite_where=sa.text('verified_at IS NOT NULL'))
        batch_op.create_index(batch_op.f('idx_correction_logs_reviewer'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_correction_logs_field'), ['extracted_field_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_correction_logs_exported'), ['retraining_exported'], unique=False)
        batch_op.create_index(batch_op.f('idx_correction_logs_document'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_correction_logs_action'), ['action'], unique=False)
        batch_op.alter_column('reviewer_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('document_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('extracted_field_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('audit_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_action_type'))

    op.drop_table('audit_log_entries')
    # ### end Alembic commands ###
